eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/
spring:
  application:
    name: user-config
  rabbitmq:
    host: localhost
    port: 5671
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
management:
  security:
    enabled: false
server:
  port: 8881
