server:
  port: 8761
  node1: ${eureka.instance.hostname}
  node2: eureka-server-node2
  node3: eureka-server-node3

eureka:
  instance:
    hostname: eureka-server-node1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${server.node1}:${server.port}/eureka/,http://${server.node2}:${server.port}/eureka/,http://${server.node3}:${server.port}/eureka/

spring:
  profiles:
    active: node1