server:
  port: 6002

eureka:
  instance:
    hostname: eureka-server-node2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server-node1:6001/eureka/,http://eureka-server-node2:6002/eureka/,http://eureka-server-node3:6003/eureka/
spring:
  profiles:
    active: node2