spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jxzsxsp/spring-cloud-study/
          search-paths: resources
          username: your username
          password: your password
      label: master
server:
  port: 6100
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-node1:6001/eureka/,http://eureka-server-node2:6002/eureka/,http://eureka-server-node3:6003/eureka/

